### ISSUE TITLE
Add a git tag

### ISSUE THREAD

**Issue by hadim** [KarypisLab/METIS#13]
I am trying to build a conda package that depends on the `master` branch of this repo (not 5.1.0). Could you add a tag to this repo such as 5.2.0 or 5.1.1 so I can use it for the metis conda package at https://github.com/conda-forge/metis-feedstock/blob/master/recipe/meta.yaml

Thank you

**Comment by hadim** [comment]
ping @karypis

**Comment by gruenich** [comment]
Adding a Git tag for having a Git tag is ill-advised. You are actually asking for a new release of METIS. Given that METIS 5.1.0 is from 2013 and the accumulated changes over these seven years, this might be a good idea. But karypis has to decide whether he has the time to make a release (and adding a Git tag).

**Comment by hadim** [comment]
The current master branch is used in different libs. Adding a git tag just allow proper versioning to package it. You can also call it a new release a new version it's the same.

Without a git tag/new release I can't package METIS.

**Comment by hadim** [comment]
If the release process is too cumbersome or heavy to do then a simple git tag would be sufficient. Since anyway master is already used downstream by different libs.

**Comment by hadim** [comment]
I am curious to understand why a git tag only is ill-advised? Isn't better than building a downstream lib from a git tag than a master branch? Especially if some libs are already using master?

**Comment by hadim** [comment]
Here is the associated PR for the conda package: https://github.com/conda-forge/metis-feedstock/pull/30

I am also happy to continue the discussion about the usefulness of a git tag.

**Comment by karypis** [comment]
I merged the develop branch into master and added tags both in metis and gklib.

**Comment by hadim** [comment]
Thank you @karypis
