### ISSUE TITLE
[explanation] Is there any explanation of how Match_SHEM is coded

### ISSUE THREAD

**Issue by yiakwy-xpu-ml-framework-team** [KarypisLab/METIS#28]
METIS is awesome and very useful for discrete math community. Now I am building a software dealing with dynamic weights of computation ML graph. Our operations and tensor are highly optimized and have shared codes in hardware, hence summation of the cost is dynamic. Also we have topical order constrain.

We have develop a solver. But to utilize the Multi-level framework, one of useful things I am trying to understand is how "idx_t Match_SHEM(ctrl_t *ctrl, graph_t *graph)"  and "refine_KwayPartition" is coded. Is there any explanation here ? @karypis

**Comment by karypis** [comment]
There is no other explanations beyond the research papers and the code itself.
