### ISSUE TITLE
undefined reference to `METIS_NodeND'

### ISSUE THREAD

**Issue by jiapei-nexera** [KarypisLab/METIS#33]
Trying to build [https://github.com/ceres-solver/ceres-solver](https://github.com/ceres-solver/ceres-solver) without **SuiteSparse BUT METIS** , I got: 

```console
undefined reference to `METIS_NodeND'
```

**Comment by jiapei-nexera** [comment]
Might this be the solution?

[https://github.com/mfem/mfem/issues/698](https://github.com/mfem/mfem/issues/698) ?

**Comment by jiapei-nexera** [comment]
```ImportError: /usr/local/lib/libmetis.so: undefined symbol: gk_jbufs```

Looks like libmetis.so and **GKlib** are now separated, and **libmetis.so** replies on **GKlib** ...

**Comment by karypis** [comment]
The ceres-solver needs to be updated to reflect that GKlib is not included directly in Metis and it is its own library.
