### ISSUE TITLE
Is there an official METIS website

### ISSUE THREAD

**Issue by afabri** [KarypisLab/METIS#37]
On the wikipedia METIS [page ](https://en.wikipedia.org/wiki/METIS) I see an external link going to  [this page](http://glaros.dtc.umn.edu/gkhome/views/metis) at umn.edu.       Is one of them more official than the other?  Is it a fork? 
I ask as we want to put the best link on the third party libraries [page ](https://doc.cgal.org/latest/Manual/thirdparty.html#thirdpartyMETIS)for CGAL.  When I get a reply I can also change on the wikipedia.

**Comment by PMeira** [comment]
It seems to be offline now, but this is from the sidebar of the [archived](http://web.archive.org/web/20220331233857/http://glaros.dtc.umn.edu/gkhome/) home page (http://glaros.dtc.umn.edu/gkhome/) of the site you linked (which is indeed listed in a lot of places besides Wikipedia):

> We will be slowly moving our codes to [KarypisLab's GitHub repository](https://github.com/KarypisLab). (3/20/18)

**Comment by leofang** [comment]
We also noticed the METIS website is down for some time. What's worse now is we used to link to the website, but because the link is dead, our link checker bot fails, and so I came and found this issue seeking for guidance. Should we change to link to this repo from now on?

**Comment by nabw** [comment]
Hi, I just noticed that I raised the same issue in Parmetis (https://github.com/KarypisLab/ParMETIS/issues/19). Commenting to avoid keeping the issues disconnected.

It is also very important as the current lack of tags has made all previous versions of the library disappear. @leofang  did you manage to find some other temporary links to the previous ones? 

Thanks!

**Comment by leofang** [comment]
It seems it's backed up by webarchive: http://web.archive.org/web/20211119110155/http://glaros.dtc.umn.edu/gkhome/metis/metis/download

**Comment by nabw** [comment]
Amazing, I actually looked for it at archive, but couldn't find it. Thank you very much! 

Probably the issue should stay open anyway.

**Comment by karypis** [comment]
The original website is now up again.
