### ISSUE TITLE
Bug in genmmd (multiple minimum external degree) function

### ISSUE THREAD

**Issue by npotravkin** [KarypisLab/METIS#46]
Function return wrong ordering on simplest graph. Results depend on input garbage in working parameters.

example:

    const idx_t neqns = 2;
    idx_t xadj[3]={1,2,3};
    idx_t adjncy[2] = {2,1};

    idx_t delta = 1;
    idx_t maxint = IDX_MAX;

    const idx_t nvtxs = 2;
    std::unique_ptr<idx_t[]> perm(new idx_t [nvtxs+5]);
    std::unique_ptr<idx_t[]> iperm(new idx_t [nvtxs+5]);
    std::unique_ptr<idx_t[]> head(new idx_t [nvtxs+5]);
    std::unique_ptr<idx_t[]> qsize(new idx_t [nvtxs+5]);
    std::unique_ptr<idx_t[]> list(new idx_t [nvtxs+5]);
    std::unique_ptr<idx_t[]> marker(new idx_t [nvtxs+5]);
    idx_t nofsub;
    
    bool is_bug_produced = true;
    if(is_bug_produced){
        for(idx_t i=0;i<nvtxs+5;++i) head[i] = 2;
    }else{
        for(idx_t i=0;i<nvtxs+5;++i) head[i] = -2;
    }

    genmmd(neqns,xadj,adjncy,iperm.get(),perm.get(),delta,head.get(),qsize.get(),list.get(),marker.get(),maxint,&nofsub);

**Comment by jsf67** [comment]
I'm pretty sure this is the same bug I'm hitting.  In the case I'm testing genmmd was called with a fully connected graph of size 3.
The point of failure is line 107: mdeg_node = head[mdeg];  with mdeg=4 even though neqns=3
That sets mdeg to garbage from past the end of the head[] array, so crash or not crash depends on what garbage happens to be past the end of that array, as in the above example.  A zero or negative value past the end of head[] is safe, while a positive value may corrupt the output or may corrupt nearby memory.

I think the simple fix would be a line added directly after line 97 to do:
if (mdlmt>neqns) mdlmt=neqns;

**Comment by jsf67** [comment]
I think that as long as delta is 1, the bug in mmdint that was fixed 2019-06-03 covered up this bug in genmmd.

So the many users who have not updated to the 2019-06-03 or later version aren't seeing this bug.  But once you have the 2019-06-03 correction, this bug becomes very serious and often causes seg faults in typical calling code.

**Comment by karypis** [comment]
Thanks for this. See if the fix addresses the issue.

**Comment by npotravkin** [comment]
Issue is fixed on my example.
