### ISSUE TITLE
Impact of edge weights assignemnt

### ISSUE THREAD

**Issue by hankstag** [KarypisLab/METIS#47]
Hello,

Thank you for sharing this valuable work! I am having some trouble understanding the behavior of metis with edge wights assigned. I suspect I am using the wrong options that caused this.
I am trying the `METIS_PartGraphKway` function on a toy undirected, weighted graph like this:
![Screenshot 2022-09-22 110925](https://user-images.githubusercontent.com/6883726/191650059-9f40260d-1336-4561-82d3-2e3f30b114e3.png)
where the red edges have weight 1, and black edges have weight 10. 
I was expecting the function would produce a partition that separate the top-left corner vertex, however it is assigned the top-mid vertex a single group. And I also noticed that the function produces the same output when I set edge weights as 10 for all. 
```
options[METIS_OPTION_PTYPE] = METIS_PTYPE_KWAY;
options[METIS_OPTION_OBJTYPE] = METIS_OBJTYPE_CUT;
options[METIS_OPTION_CTYPE] = METIS_CTYPE_SHEM;
options[METIS_OPTION_IPTYPE] = METIS_IPTYPE_GROW;
options[METIS_OPTION_RTYPE] = METIS_RTYPE_FM;
options[METIS_OPTION_DBGLVL] = 255;
options[METIS_OPTION_UFACTOR] = 1000; 
options[METIS_OPTION_MINCONN] = 0;
options[METIS_OPTION_CONTIG] = 0;
options[METIS_OPTION_SEED] = -1;
options[METIS_OPTION_NITER] = 100;
options[METIS_OPTION_CCORDER] = 0;
options[METIS_OPTION_NCUTS] = 5;
```

Any help would be appreciated, thank you!

**Comment by karypis** [comment]
Metis is known not to work well on small graphs; as its heuristics are not optimized for such cases.
