### ISSUE TITLE
Incorrect part number with `nparts == 1`

### ISSUE THREAD

**Issue by cedhub** [KarypisLab/METIS#49]
Looks like there is a bug in (at least) `METIS_PartMeshDual()`, leading the `epart` and `npart` vectors to contain 1s instead of 0s, with `options[METIS_OPTION_NUMBERING] = 0`.
When `nparts > 1`, the vectors actually contain 0s and 1s.

I'm using version 5.1.0, along with Apple clang version 14.0.0.

Is this a normal behaviour ? If yes, I couldn't find it in the manual.

Thanks !

**Comment by karypis** [comment]
This was an unhandled corner case. It should be fixed. Please check.

**Comment by cedhub** [comment]
Now it works fine. Thank you !
