### ISSUE TITLE
How to strictly partition a graph into small graphs and each graph has same vertices?

### ISSUE THREAD

**Issue by MaxLykoS** [KarypisLab/METIS#55]
I want to transform a mesh(a 3D geometry in rendering) into a sets of triangles. Each set contains 64 triangles, which is also called a cluster or meshlet. So I conveted the mesh into a graph. For example the mesh has 768 triangles, so what I expect is 768/64 = 12 clusters. 
However the returned part array shows the partition results arent strictly equal size. Some clusters have 65 vertices and some have 63, although most of the clusters has 64 vertices. So how do I force the Metis algorithm to return equal size clusters?
Function is METIS_PartGraphRecursive.

**Comment by karypis** [comment]
Unfortunately, Metis does not support this.
