### ISSUE TITLE
5.2.1 is not finding GKlib.h

### ISSUE THREAD

**Issue by cponder** [KarypisLab/METIS#61]
Running these commands:
```
mkdir INSTALL
VERSION_METIS=5.2.1
curl --retry 5 -fSsL "https://github.com/KarypisLab/METIS/archive/refs/tags/v${VERSION_METIS}.tar.gz" | tar xz
cd METIS-5.2.1
git clone git@github.com:KarypisLab/GKlib.git GKlib                    # Since we don't have a real release.
make config shared=1 prefix=$(realpath ../INSTALL)  gklib_path=$PWD/GKlib
make install                                                           # Evidently gklib_path gets ignored.
```
gives this error
```
In file included from /home/scratch.cponder_sw/Containers/ubuntu-pgi-openmpi.selene/Temp/FOO/METIS-5.2.1/libmetis/auxapi.c:12:0:
/home/scratch.cponder_sw/Containers/ubuntu-pgi-openmpi.selene/Temp/FOO/METIS-5.2.1/libmetis/metislib.h:17:10: fatal error: GKlib.h: No such file or directory
 #include <GKlib.h>
          ^~~~~~~~~
compilation terminated.
libmetis/CMakeFiles/metis.dir/build.make:78: recipe for target 'libmetis/CMakeFiles/metis.dir/auxapi.c.o' failed
make[3]: *** [libmetis/CMakeFiles/metis.dir/auxapi.c.o] Error 1
```

**Comment by cponder** [comment]
I did manage to get it to build by installing the GKlib separately and pointing the variable to ```/usr/local```.
I was trying to use it incorrectly before -- pointing to the source-directory rather than the installation directory, so probably the failure was that it was looking for ```$(gklib_path)/include```.
I'm closing this issue.

**Comment by cponder** [comment]
I did manage to get it to build by installing the GKlib separately and pointing the variable to /usr/local.
I was trying to use it incorrectly before -- pointing to the source-directory rather than the installation directory, so probably the failure was that it was looking for $(gklib_path)/include.
I'm closing this issue.

**Comment by Fern-Parker** [comment]
The reason may be that you have no directories: ~/local/lib, ~/local/include, ~/local/bin, you need to create these directories， then perform: 
    make config prefix=~/local
    make
    make install
The idea is that the built header files of GKlib are in  ~/local/include
