### ISSUE TITLE
Metis download

### ISSUE THREAD

**Issue by goodluck-hojae** [KarypisLab/METIS#93]
Hi,
I tried to follow the ClusterGCN project's instruction which requires to install "metis" library as a prerequisite.
However, metis official website/download page (http://glaros.dtc.umn.edu/gkhome/metis/metis/download) seems to be down :disappointed:
Could anyone help?
Thank you

**Comment by gfaster** [comment]
You could either download the [latest release](https://github.com/KarypisLab/METIS/releases/tag/v5.2.1) or look in your distro's repositories. For Ubuntu and Debian it's `libmetis-dev`, there's a `metis` package in the AUR, nixpkgs, and Guix.

If you're on Windows, you'll probably have to build from source.

**Comment by goodluck-hojae** [comment]
Thank you so much.
I resolved issue by building the project with the tag version 5.1.1.
